name: CI

#on: [push]
on: 
  push:
    tags:
    - '*'


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag: v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
