name: CI

#on: [push]
on: 
  push:
    tags:
    - '*'


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!; zip -r -X archive.zip test
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "archive.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
