name: CI

on: 
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        sudo apt-get update -y
        sudo apt-get install -y httpie
        echo "dsym-1574174057-b155b1.6.4" | http POST dsym.dev01.pmagentur.com/nmz7hmdk6rgbd5rq
