name: php-lint

on:
  pull_request:
    types: open

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: php-lint
    - uses: michaelw90/php-lint@master
